name: front-github-actions
on:
  push:
    branches:
      - airport
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: install
        run: yarn install
